### ISSUE TITLE
pack https://github.com/Microsoft/omi/tree/master/Unix/share to /opt/omi/share, that's need for python provider omigen

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi-script-provider#10]
/opt/omi/share/omischema/CIM_Schema.mof doesn't exist in released build: https://github.com/Microsoft/omi/releases/tag/v1.2.0-35.

here is what we get:
```
/tmp/samples/xyz_frog
root@py64-cent7-01  # /opt/omi/bin/omigen_py schema.mof XYZ_Frog
failed to open file: /opt/omi/share/omischema/CIM_Schema.mof
```

Possible fix place for this issue:
https://github.com/Microsoft/omi/blob/master/Unix/installbuilder/datafiles/Base_OMI.data#L21 
https://github.com/Microsoft/omi/blob/master/Unix/installbuilder/datafiles/Base_OMI.data#L40

**Comment by alinbalutoiu** [comment]
More details about this can be found here: https://github.com/Microsoft/omi-script-provider/pull/18#pullrequestreview-65907382

**Comment by JumpingYang001** [comment]
@alinbalutoiu , so we need to copy the files to /opt/omi/share/omischema/ manually, right?

**Comment by alinbalutoiu** [comment]
@JumpingYang001 as Jeff said in the review, if you want to build a python provider from scratch, you will need to build OMI from source. When you build OMI from source you will automatically get all the required files needed for omigen.
