### ISSUE TITLE
some old OS like Redhat/CentOS 5/6 default python version is lower than 2.7

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi-script-provider#17]
some old OS like Redhat/CentOS 5/6 default python version is lower than 2.7
even it can update to 2.7 through some ways, and need to set some soft link for them.

This is some trouble for our testing: we need a fixed steps to upgrade them to python2.7 and make sure the steps doesn't effect other tools like yum, now testing is blocked on Redhat/CentOS 5/6 for the default python is not 2.7.

If we want to support Redhat/CentOS 5/6 for python script provider, we need to make sure customer follow our upgrade python2.7 steps to make sure we have same environment and avoid different steps caused error.

**Comment by JumpingYang001** [comment]
BTW, we have meet issue on CentOS6:
```
root@py64-cent6-t1  # python /opt/omi/lib/client.py XYZ_Frog
Traceback (most recent call last):
  File "/opt/omi/lib/client.py", line 7, in <module>
    import omi
ImportError: No module named omi
```

**Comment by lilyfang** [comment]
For this release, we will just support the platform with python 2.7 version as default. With the feedback from the customers, we will decide if and how to expand to other python versions.

**Comment by JumpingYang001** [comment]
@lilyfang , sounds great! thanks.

**Comment by jeffaco** [comment]
Yup. For this release, we've decided that the vendor must support Python 2.7. So the old Linuxes won't be supported with the OMI script provider. As Li said, we'll reevaluate after release after collecting clear customer requirements.

Closing this issue.
