### ISSUE TITLE
[All Platforms][1.1.1-12] omireg register provider failed: "python2.7: can't open file 'client.py'" and "Server::open - exec failed: 2: "No such file or directory""

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi-script-provider#38]
**ENV:**
- All platforms

**Repos:**
1.Install omi: `\\redmond\wsscfs\OSTCData\Builds\omi\develop\1.4.0-3`
2.Install python script build: `\\redmond\wsscfs\OSTCData\Builds\omiscriptprovider\develop\1.1.1-12`;
3.Currently copy customized python provider to /opt/omi/lib;
4.Switch to above directory: "cd /opt/omi/lib";
5.Register Python provider but failed: "/opt/omi/bin/omireg --Python xyz_frog" 
```
~
root@omi64-sles12-t1  # /opt/omi/bin/omireg --Python xyz_frog
python2.7: can't open file 'client.py': [Errno 2] No such file or directory
/opt/omi/bin/omireg: MI_Module.schemaDecl is null

~
root@omi64-sles12-t1  # find / -name client.py
/opt/omi/lib/client.py
/usr/lib64/python3.4/http/client.py
/usr/lib64/python3.4/site-packages/speechd/client.py
/usr/lib64/python3.4/xmlrpc/client.py
~
root@omi64-sles12-t1  # python
Python 2.7.7 (default, Jun 23 2014, 13:38:05) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

omi64-cent5-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
-- | -- | --
omi86-cent5-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-cent6-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-cent6-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-cent7-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-deb7-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-deb7-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-deb8-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-deb8-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-ora5-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-ora5-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-ora6-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-ora6-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-ora7-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-sles11-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-sles11-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-sles12-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-rhel5-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-rhel5-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-rhel6-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-rhel6-t1 | Server::open - exec failed: 2: "No such file or directory"/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-rhel7-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-ubun12-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-ubun12-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-ubun14-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-ubun14-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi86-ubun16-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True
omi64-ubun16-t1 | python2.7: can't open file 'client.py': [Errno 2] No such file or directory/opt/omi/bin/omireg: MI_Module.schemaDecl is null | True

**Comment by JumpingYang001** [comment]
omi64-deb9-t1 also has this issue.

**Comment by alinbalutoiu** [comment]
Please check with the latest build (1.1.1-13 at the moment) to see if this issue still exists.

**Comment by JumpingYang001** [comment]
we will wait 1.1.1-14 tomorrow since 1.1.1-13 doesn't contains the fix, thanks.

**Comment by alinbalutoiu** [comment]
Have you tested it? I've updated this build to contain the fix and it worked for me, that's why I asked you to also test it if you can, thanks.

**Comment by JumpingYang001** [comment]
I see the build exist before I merge the fix to master, have you overwrite it after I merge it to master?
Anyway, we will test the fix tomorrow, thank you!

**Comment by JumpingYang001** [comment]
Verified on \\redmond\wsscfs\OSTCData\Builds\omiscriptprovider\develop\1.1.1-14 
python2.7 OS are fixed now.
But we found non-python2.7 OS has this issue:
Fail: 
CentOS 5 (x64/x86), CentOS 6 (x64/x86)
Oracle 5 (x64/x86), Oracle 6 (x64/x86)
Debian 6 (x64/x86), 
SUSE 10 (x64/x86), SUSE 11 (x64/x86), 
Rhel 5 (x64/x86), Rhel 6 (x64/x86)

**Comment by JumpingYang001** [comment]
track non-python2.7 OS issue in #43 , close this issue.
