### ISSUE TITLE
[DOC] need to document "export CPPFLAGS="-DPRINT_BOOKENDS""

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi-script-provider#50]
According to #45 , we should document "export CPPFLAGS="-DPRINT_BOOKENDS""

**Comment by JumpingYang001** [comment]
we need to provider something like Environment value to enable the SCX_BOOKEND logs, otherwise user cannot get what's wrong and cannot provide more information for their issues.

**Comment by EMumau** [comment]
I don't think that there's a good reason to document this.

- This compiler flag only turns on debugging output that pertains to the script provider infrastructure.
- This is not helpful for an end user developing a provider.  Or rather, developers of providers have many better options for debugging.
- The output is only sent to stdout.  Therefore, the output is only available when running the omiserver from a terminal window.
- Specific omiserver options redirect stdout which disables this feature.

**Comment by JumpingYang001** [comment]
@EMumau , agreed, all right, just close it.

**Comment by JumpingYang001** [comment]
@EMumau , BTW, do we have any log for python provider only? or we only can trace issues from omi logs?
