### ISSUE TITLE
[DOC] typo in python script will get error, but you don't know where cause the issue.

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi-script-provider#62]
This is an issue for python developer, when they did something wrong, but they don't know where, I mean if there is a way to make things easy to troubleshooting, it will be better. :)
My team member meet an issue, he typo something in python like:
` be = BookEnd ('TestClass_AllDMTFArrays_GetInstance') `
to
` be = BoolEnd ('TestClass_AllDMTFArrays_GetInstance')`

You will get error:
```
/opt/omi/lib
root@omi64-cent7-01  # /opt/omi/bin/omicli gi root/cimv2 { TestClass_AllDMTFArrays  v_Key 1 }
/opt/omi/bin/omicli: result: MI_RESULT_FAILED
instance of OMI_Error
{
    OwningEntity=OMI:CIMOM
    MessageID=OMI:MI_Result:1
    Message=A general error occurred, not covered by a more specific error code.
    MessageArguments={}
    PerceivedSeverity=7
    ProbableCause=0
    ProbableCauseDescription=Unknown
    CIMStatusCode=1
    OMI_Code=1
    OMI_Category=0
    OMI_Type=MI
    OMI_ErrorMessage=A general error occurred, not covered by a more specific error code.
} 
```

**Comment by c64cosmin** [comment]
The server side errors should not get forwarded to the client. That is a development specific feature and should be used as such. Compiling with PRINT_BOOKENDS will trace the exceptions in stdout, but should never be used in release, deployed.

I will document the way a developer needs to use and build, the server and script provider in order to get information about the exceptions risen in Python.

**Comment by JumpingYang001** [comment]
OK, it would better if we can document this: thanks.

**Comment by c64cosmin** [comment]
@JumpingYang001 Implemented a solution for developers only, must document and will push PR.

**Comment by JumpingYang001** [comment]
@c64cosmin , is this in your PR #70 ? if yes, we can close it, thanks.

**Comment by c64cosmin** [comment]
@JumpingYang001 PR #72 is the solution.
Thank you.

**Comment by JumpingYang001** [comment]
Merged to master.
