### ISSUE TITLE
[Memory leak] python memory usage increase from 0.4 to 1.6 after querying 18 hours

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi-script-provider#63]
**Memory leak for python process?** python memory usage increase from 0.4 to 1.6 after querying 18 hours
Querying script:
```
root@omi64ub16-dev1:/opt/omi/lib/omi_tester# for i in {1..1000000}; do /opt/omi/bin/omicli iv root/cimv2 { OMI_Tester Key "ONE" } Func1 { In1 "test" }; done
```

Memory usage comparison:
```
root@omi64ub16-dev1:~# ps -aux|grep omi
root     37946  0.1  0.4  44780  9780 ?        S    01:22   0:02 python2.7 client.py omi_tester 6000 D589E6BE033B395310B2A45DE9111465
root@omi64ub16-dev1:~# ps -aux|grep omi
root     37946  0.1  1.6  68588 33140 ?        S    01:22   1:58 python2.7 client.py omi_tester 6000 D589E6BE033B395310B2A45DE9111465
root@omi64ub16-dev1:~# 

```

code I used:
```
def OMI_Tester_Func1 (
    context, nameSpace, className, methodName, instanceName, parameters):
    be = BookEnd ('OMI_Tester_Func1')
    BookEndPrint ('**********')
    BookEndPrint ('**********')
    BookEndPrint ('**********')
    BookEndPrint ('**********')
    BookEndPrint ('**********')

    outParams = context.NewParameters ('OMI_Tester', 'Func1')
    keyvalue = instanceName.GetValue('Key')
    in1 = parameters.GetValue('In1')
    outParams.SetValue ('Out1', MI_String (in1.value))
    outParams.SetValue ('Out2', MI_Uint32 (1))
    outParams.SetValue ('Out3', MI_Boolean (True))
    outParams.SetValue ('MIReturn', MI_Uint32 (0))
    context.PostInstance (outParams)
context.PostResult (MI_RESULT_OK)

root@omi64ub16-dev1:/opt/omi/lib/omi_tester# /opt/omi/bin/omicli iv root/cimv2 { OMI_Tester Key "ONE" } Func1 { In1 "test" }
instance of Func1
{
    Out1=test
    Out2=1
    Out3=true
    ReturnValue=0
}
```

**Comment by EMumau** [comment]
I will be looking into this matter today.

**Comment by EMumau** [comment]
A built a primitive memory checking tool into this project at the beginning.  All elements inherits from MI_ValueBase.  There is a counter that is incremented whenever an object is created and decremented when it is destroyed.  When I run python/test/test.py, all the object count reaches zero when the program finishes.  When running a provider through the omiserver, there are a handful of objects that aren't deleted when the provider shuts down.  I've tracked these objects to the schema decl.  This shouldn't be an issue.  The schema decl only loads at startup, so it won't grow during runtime.  And at shutdown, all of the memory is released.  I work still work to fix this issue.  The growth would be the result of incorrect reference counting in the Python layer.  I will have to go through each python to C and C to Python interface to identify instances where the Python reference counting is done incorrectly.  This will take some effort.  The Python documentation is lacking, as are the tools.

However, I feel that an 18 hour run for a Python provider is an unrealistic test.  I do not feel that this leak should block release.  It should be noted in the release notes.  And I will continue to work on locating the leaks.

**Comment by JumpingYang001** [comment]
@EMumau , omiserver or omiagent works fine, I mean Python process always exist and its memory increase.
Python process in ps command: `python2.7 client.py omi_tester 6000 D589E6BE033B395310B2A45DE9111465`
Looks like this Python process will not exit when I ran `for i in {1..1000000}; do /opt/omi/bin/omicli iv root/cimv2 { OMI_Tester Key "ONE" } Func1 { In1 "test" }; done`

**Comment by JumpingYang001** [comment]
so we should check python process which is launched by omiagent , we should not omi related processes.

**Comment by JumpingYang001** [comment]
I will verify if #71 fix the issue or not when build come out, thanks.

**Comment by JumpingYang001** [comment]
@EMumau , `python2.7 client.py omi_tester 6000 D589E6BE033B395310B2A45DE9111465` this process will exist for about 1 minute if there is no query coming in, so we should document this for the query interval with python provider.
- If query interval is more than 1 minute, then python2.7 process will exit, so it will be released.
- when query interval is less 1 minute, it will always exist, and I got memory leak for this scenario.

You can document it or fix the less 1 minute memory leak issue, that depends on you and our customers' real requirements, thanks. :)

**Comment by JumpingYang001** [comment]
I have verified on \\redmond\wsscfs\OSTCData\Builds\omiscriptprovider\develop\1.1.1-44, this issue still exist.
I used memleak to detect memory leak, attach my logs, hope it can be helpful.
[memleax_start.txt](https://github.com/Microsoft/omi-script-provider/files/1481482/memleax_start.txt)
[memleax_Callstack_statistics.txt](https://github.com/Microsoft/omi-script-provider/files/1481483/memleax_Callstack_statistics.txt)

**Comment by JumpingYang001** [comment]
I am thinking do we need to free the object new in python script?
For example, these objects? or they are freed in C layer?
```
be = BookEnd ('OMI_Tester_Func1')
outParams = context.NewParameters ('OMI_Tester', 'Func1')
instance = context.NewInstance ('XYZ_ColorBase')
```

**Comment by JumpingYang001** [comment]
Maybe we need some tool like [Pympler](https://pypi.python.org/pypi/Pympler) and [objgraph](https://pypi.python.org/pypi/objgraph) to detect more detail things. 
BTW, one surprise thing is that the python program sometimes come down: (so now it looks very strange, one possible reason is that the python garbage free some memory, and I am not sure if it will be a big problem in production environment or not.)
```
root@omi64ub16-dev1:~# ps -aux|grep python
root     20663  0.3  0.9 218840 19544 ?        S    Nov16   0:10 python2.7 client.py omi_tester 6001 7DD73394F3EFBCAF167635E66C5EAA9D
root     22788  0.0  0.0  14228   932 pts/2    S+   00:05   0:00 grep --color=auto python
root@omi64ub16-dev1:~# ps -aux|grep python
root     20663  0.4  0.8 219096 17608 ?        S    Nov16   0:15 python2.7 client.py omi_tester 6001 7DD73394F3EFBCAF167635E66C5EAA9D
root     35103  0.0  0.0  14228   944 pts/2    S+   00:14   0:00 grep --color=auto python
root@omi64ub16-dev1:~# ps -aux|grep python
root     20663  0.4  0.8 219096 17608 ?        S    Nov16   0:15 python2.7 client.py omi_tester 6001 7DD73394F3EFBCAF167635E66C5EAA9D
root     35805  0.0  0.0  14228   960 pts/2    S+   00:14   0:00 grep --color=auto python
root@omi64ub16-dev1:~# ps -aux|grep python
root     20663  0.4  0.8 219096 17608 ?        S    Nov16   0:16 python2.7 client.py omi_tester 6001 7DD73394F3EFBCAF167635E66C5EAA9D
root     36882  0.0  0.0  14228  1012 pts/2    S+   00:15   0:00 grep --color=auto python
root@omi64ub16-dev1:~# ps -aux|grep python
root     20663  0.5  0.6 219352 13396 ?        S    Nov16   0:21 python2.7 client.py omi_tester 6001 7DD73394F3EFBCAF167635E66C5EAA9D
root     49145  0.0  0.0  14228   852 pts/2    S+   00:23   0:00 grep --color=auto python
root@omi64ub16-dev1:~# ps -aux|grep python
root     20663  0.5  0.6 219352 12628 ?        S    Nov16   0:21 python2.7 client.py omi_tester 6001 7DD73394F3EFBCAF167635E66C5EAA9D
root     51284  0.0  0.0  14228   864 pts/2    S+   00:25   0:00 grep --color=auto python
root@omi64ub16-dev1:~# ps -aux|grep python
root     20663  0.5  0.6 219352 12628 ?        S    Nov16   0:21 python2.7 client.py omi_tester 6001 7DD73394F3EFBCAF167635E66C5EAA9D
root     51352  0.0  0.0  14228   972 pts/2    S+   00:25   0:00 grep --color=auto python
```

**Comment by JumpingYang001** [comment]
That say I don't know who will use python provider and how is their provider like, if I can have a real production which is wrote by python with script provider, then we can test and check how the memory usage goes on, thanks.
So the most important one is the requirements: how frequently they query: less 1 minute or more than 1 minute is the point.

To identify less 1 minute memory leak issue really impact production environment or not, we need at least running for 3~5 days or more to check the result, thanks.
I am running following script, let's see the result after several days later:
```
while true; do /opt/omi/bin/omicli iv root/cimv2 { OMI_Tester Key "ONE" } Func1 { In1 "test" }; sleep 5; done
while true; do ps -aux|grep python|grep -v grep>> /root/pythonmemleak.log;date>> /root/pythondate.log;sleep 60; done
```

**Comment by JumpingYang001** [comment]
one query per 5 seconds, querying 1 hour: python process keep on 8808kb. but let's wait 3~5 days data to final conclude the final affected result.

**Comment by yakman2020** [comment]
0.4 to 1.6 whats?

Python has a lazy garbage collector. If those numbers are megabytes I would expect that is normal operation.

It will probably grow over time due to fragmentation, then sharply reduce etc.

**Comment by EMumau** [comment]
The units of measure are percentage of system memory.  Test is using ps -aux to measure.
I had the same question.

**Comment by JumpingYang001** [comment]
I'll give you result for these scenarios:
1 query per second for at least running 1 day.
1 query per 5 seconds.for at least running 1 day.
query after query without sleep at least running 2.~3 days.
And then make a conclusion.

**Comment by JumpingYang001** [comment]
### Here is the 1 query per 5 seconds result:
8808->9584->9792->10048
duration: **about 18 hours:** Thu Nov  9 01:48:54 PST 2017 ->Thu Nov  9 19:18:55 PST 2017

**Note:** An interesting thing is that the memory come down to 8896kb after I stop the above query script.

### Now I am running the "query after query without sleep at least running 2~3 days." test, let's wait the result to check if it will go up to 100% memory usage or not, thanks.
```
while true; do /opt/omi/bin/omicli iv root/cimv2 { OMI_Tester Key "ONE" } Func1 { In1 "test" }; done
while true; do ps -aux|grep python|grep -v grep>> /root/pythonmemleak.log;date>> /root/pythondate.log;sleep 60; done
```

**Comment by JumpingYang001** [comment]
I get following results now, but I don't know why the python process exit and new again, is it by design?

Duration: **about 43 hours**: Sat Nov 18 00:13:59 PST 2017 -> Sun Nov 19 19:24:25 PST 2017
```
root     57178  0.0  0.4  44516  8896 ?        S    00:13   0:00 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
root     57178  0.2  0.4  44516  9684 ?        S    00:13   0:00 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
root     57178  0.2  0.4  45028 10120 ?        S    00:13   0:02 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
root     57178  0.2  0.5  45284 10376 ?        S    00:13   0:03 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
root     57178  0.2  0.5  45540 10632 ?        S    00:13   0:05 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
root     57178  0.2  0.5  45796 10888 ?        S    00:13   0:06 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
root     57178  0.2  0.5  46052 11144 ?        S    00:13   0:07 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
root     57178  0.2  0.5  46308 11400 ?        S    00:13   0:09 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
......

root     57178  0.2  1.1  58852 24100 ?        S    00:13   1:14 python2.7 client.py omi_tester 6000 E760BC29B63C26142ACEC8732BCAEE51
root     21734  0.2  0.4  44516  8984 ?        S    10:26   0:00 python2.7 client.py omi_tester 6000 F3658623887F18B2106566DCF073B0D8
......

root     21734  0.2  0.8  51428 16544 ?        S    10:26   0:36 python2.7 client.py omi_tester 6000 F3658623887F18B2106566DCF073B0D8
root     21290  0.2  0.4  44516  8988 ?        S    15:24   0:00 python2.7 client.py omi_tester 6000 484FDECE62F2614A0687CD996A08F683
......

root     21290  0.2  0.4  45028 10148 ?        S    15:24   0:03 python2.7 client.py omi_tester 6000 484FDECE62F2614A0687CD996A08F683
root     61324  0.2  0.4  44516  8968 ?        S    15:53   0:00 python2.7 client.py omi_tester 6000 CFB0C8C7516F19EE0186350B68B528D5
......

root     61324  0.2  1.5  66020 31056 ?        S    Nov18   1:51 python2.7 client.py omi_tester 6000 CFB0C8C7516F19EE0186350B68B528D5
root     30304  0.2  0.4  44516  8996 ?        S    07:05   0:00 python2.7 client.py omi_tester 6000 92670DCE7D94825F0C2D03A6F77717A4
......

```

**Comment by JumpingYang001** [comment]
Everything looks works fine except I got 2079908 ERROR messages in miclient.log like "2017/11/19 04:55:39 [30210,30210] ERROR: null(0): EventId=20106 Priority=ERROR Trying to thunk generic handle that has been shutdown already: 0x7ffe15dfa920"

```
root@omi64ub16-dev1:~# cat /var/opt/omi/log/miclient.log|grep ERROR|wc -l
2079908
```

You can check my environment:
omi64ub16-dev1
10.226.210.177
root
normal password we used.

**Is this error a big issue?**

**Comment by JumpingYang001** [comment]
**Following issue is due to restart omi service but the query are still querying which should be by design:**

I got some other errors in miclient.log even the query result works fine:
```
2017/11/19 21:39:55 [1412,1413] ERROR: null(0): EventId=20055 Priority=ERROR Selector_Run: 0x7f2a97efff90 Empty List
2017/11/19 21:39:55 [1414,1414] ERROR: null(0): EventId=20129 Priority=ERROR Socket connect() failed, /var/opt/omi/run/omiserver.sock, error 2
2017/11/19 21:39:55 [1414,1414] ERROR: null(0): EventId=20125 Priority=ERROR Socket connect failed, locator /var/opt/omi/run/omiserver.sock
2017/11/19 21:39:55 [1414,1414] ERROR: null(0): EventId=20119 Priority=ERROR MI Socket connector failed, operation 0x1616b60, result 1
2017/11/19 21:39:55 [1414,1414] ERROR: null(0): EventId=20123 Priority=ERROR InteractionProtocolHandler_Session_Connect failed, session 0x1615990, result 1
2017/11/19 21:39:55 [1414,1414] ERROR: null(0): EventId=20121 Priority=ERROR MI session init failed, session 0x1615990, result 1
2017/11/19 21:39:55 [1414,1415] ERROR: null(0): EventId=20055 Priority=ERROR Selector_Run: 0x7f208f6d6f90 Empty List
2017/11/19 21:39:55 [1416,1416] ERROR: null(0): EventId=20129 Priority=ERROR Socket connect() failed, /var/opt/omi/run/omiserver.sock, error 2
2017/11/19 21:39:55 [1416,1416] ERROR: null(0): EventId=20125 Priority=ERROR Socket connect failed, locator /var/opt/omi/run/omiserver.sock
2017/11/19 21:39:55 [1416,1416] ERROR: null(0): EventId=20119 Priority=ERROR MI Socket connector failed, operation 0x1db9b60, result 1
2017/11/19 21:39:55 [1416,1416] ERROR: null(0): EventId=20123 Priority=ERROR InteractionProtocolHandler_Session_Connect failed, session 0x1db8990, result 1
2017/11/19 21:39:55 [1416,1416] ERROR: null(0): EventId=20121 Priority=ERROR MI session init failed, session 0x1db8990, result 1
2017/11/19 21:39:55 [1416,1417] ERROR: null(0): EventId=20055 Priority=ERROR Selector_Run: 0x7f9a17992f90 Empty List
2017/11/19 21:39:55 [1418,1418] ERROR: null(0): EventId=20129 Priority=ERROR Socket connect() failed, /var/opt/omi/run/omiserver.sock, error 2
2017/11/19 21:39:55 [1418,1418] ERROR: null(0): EventId=20125 Priority=ERROR Socket connect failed, locator /var/opt/omi/run/omiserver.sock
2017/11/19 21:39:55 [1418,1418] ERROR: null(0): EventId=20119 Priority=ERROR MI Socket connector failed, operation 0x193cb60, result 1
2017/11/19 21:39:55 [1418,1418] ERROR: null(0): EventId=20123 Priority=ERROR InteractionProtocolHandler_Session_Connect failed, session 0x193b990, result 1
2017/11/19 21:39:55 [1418,1418] ERROR: null(0): EventId=20121 Priority=ERROR MI session init failed, session 0x193b990, result 1
2017/11/19 21:39:55 [1418,1419] ERROR: null(0): EventId=20055 Priority=ERROR Selector_Run: 0x7fa1850e6f90 Empty List
2017/11/19 21:39:55 [1420,1420] ERROR: null(0): EventId=20129 Priority=ERROR Socket connect() failed, /var/opt/omi/run/omiserver.sock, error 2
2017/11/19 21:39:55 [1420,1420] ERROR: null(0): EventId=20125 Priority=ERROR Socket connect failed, locator /var/opt/omi/run/omiserver.sock
2017/11/19 21:39:55 [1420,1420] ERROR: null(0): EventId=20119 Priority=ERROR MI Socket connector failed, operation 0xbcab60, result 1
```

**Comment by JumpingYang001** [comment]
After lots of testing, I believe there is no problem for "query after query without sleep" test, and I will close this issue.
But for "Trying to thunk generic handle that has been shutdown already: 0x7ffe15dfa920" error, we will new another issue in GitHub to track it, thanks.

**Comment by JumpingYang001** [comment]
Filed the error issue on https://github.com/Microsoft/omi/issues/448, and close this issue.
