### ISSUE TITLE
omi script provider does not compile on ubuntu 16 and probably others

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/omi-script-provider#76]
A build break. 
g++ -g -std=gnu++98 -fPIC -Wall -fvisibility=hidden -fno-strict-aliasing -fstack-protector-all -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -DENCRYPT_DECRPYT -DGSS_USE_IOV=1 -D_BSD_SOURCE -fpermissive -DPRINT_BOOKENDS=0 -I/home/v-brucc/omi/Unix/output/include -I//home/v-brucc/omi/Unix/output/include  -c -MD mi_instance.cpp -o /home/v-brucc/scriptprovider/output/obj/mi_instance.o
In file included from shared_protocol.hpp:9:0,
                 from mi_value.hpp:13,
                 from mi_instance.hpp:8,
                 from mi_instance.cpp:3:
unique_ptr.hpp: In instantiation of ‘struct util::unique_ptr_move<char [], util::default_delete<char []> >’:
shared_protocol.hpp:226:46:   required from ‘int protocol::recv(std::__cxx11::basic_string<char_t, traits>*, socket_wrapper&) [with char_t = char; traits = std::char_traits<char>]’
mi_value.hpp:876:35:   required from ‘static int scx::MI_Array<TYPE_ID>::recv(scx::MI_Array<TYPE_ID>::Ptr*, socket_wrapper&) [with unsigned int TYPE_ID = 29u; scx::MI_Array<TYPE_ID>::Ptr = util::internal_counted_ptr<scx::MI_Array<29u>, util::default_delete<scx::MI_Array<29u> > >]’
mi_instance.cpp:552:50:   required from here
unique_ptr.hpp:141:45: error: creating array of ‘char []’
     typename unique_ptr<T, D>::deleter_type m_deleter;
                                             ^
GNUmakefile:67: recipe for target '/home/v-brucc/scriptprovider/output/obj/mi_instance.o' failed
make[1]: *** [/home/v-brucc/scriptprovider/output/obj/mi_instance.o] Error 1
make[1]: Leaving directory '/home/v-brucc/scriptprovider/provider'
GNUmakefile:11: recipe for target 'SCRIPTPROVIDER' failed
make: *** [SCRIPTPROVIDER] Error 2
make -C /home/v-brucc/scriptprovider/provider install
make[1]: Entering directory '/home/v-brucc/scriptprovider/provider'
...compiling: mi_instance.o
g++ -g -std=gnu++98 -fPIC -Wall -fvisibility=hidden -fno-strict-aliasing -fstack-protector-all -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -DENCRYPT_DECRPYT -DGSS_USE_IOV=1 -D_BSD_SOURCE -DPRINT_BOOKENDS=0 -I/home/v-brucc/omi/Unix/output/include -I//home/v-brucc/omi/Unix/output/include  -c -MD mi_instance.cpp -o /home/v-brucc/scriptprovider/output/obj/mi_instance.o
In file included from shared_protocol.hpp:9:0,
                 from mi_value.hpp:13,
                 from mi_instance.hpp:8,
                 from mi_instance.cpp:3:
unique_ptr.hpp: In instantiation of ‘struct util::unique_ptr_move<char [], util::default_delete<char []> >’:
shared_protocol.hpp:226:46:   required from ‘int protocol::recv(std::__cxx11::basic_string<char_t, traits>*, socket_wrapper&) [with char_t = char; traits = std::char_traits<char>]’
mi_value.hpp:876:35:   required from ‘static int scx::MI_Array<TYPE_ID>::recv(scx::MI_Array<TYPE_ID>::Ptr*, socket_wrapper&) [with unsigned int TYPE_ID = 29u; scx::MI_Array<TYPE_ID>::Ptr = util::internal_counted_ptr<scx::MI_Array<29u>, util::default_delete<scx::MI_Array<29u> > >]’
mi_instance.cpp:552:50:   required from here
unique_ptr.hpp:141:45: error: creating array of ‘char []’
     typename unique_ptr<T, D>::deleter_type m_deleter;
                                             ^
GNUmakefile:67: recipe for target '/home/v-brucc/scriptprovider/output/obj/mi_instance.o' failed
make[1]: *** [/home/v-brucc/scriptprovider/output/obj/mi_instance.o] Error 1
make[1]: Leaving directory '/home/v-brucc/scriptprovider/provider'

**Comment by yakman2020** [comment]
@alinbalutoiu @c64cosmin @Microsoft/omi-devs

**Comment by c64cosmin** [comment]
@yakman2020 Confirmed on ubuntu 16, looking for solutions.

**Comment by alinbalutoiu** [comment]
I just checked, it's because Ubuntu 16 comes with gcc version 5 by default. You can install gcc 4 and everything would work fine on Ubuntu 16 as well. We should look anyway into fixing those issues that happen with newer compiler versions.

**Comment by JumpingYang001** [comment]
Since we provide installer packages to customer, customer needn't to build the source code themselves, so it is just affect developer, so I mark this issue as P2 which means we can fix this build issue in next release.

**Comment by JumpingYang001** [comment]
If we want to fix all 15 platforms compiling issue, that might need much more time.
Our current highest priority for issues is these 2 issues:
 - the create operation with remoting issue 
 - the python process memory leak issue.

**Comment by JumpingYang001** [comment]
If we want to fix all 15 platforms compiling issue, that might need much more time.
Our current highest priority for issues is these 2 issues:
 - the create operation with remoting issue 
 - the python process memory leak issue.

**Comment by JumpingYang001** [comment]
Since the first version of python script provider are released, I mark this issue from P2 to P1, thanks.
